### ISSUE TITLE
код не воркает

### ISSUE THREAD

**Issue by ogxxxxxxxgood** [dimondevceo/glazboga#10]
код не воркает, пробывал разные версии aiogram, всё равно не работает

Traceback (most recent call last):
  File "C:\Users\USER\Desktop\project\glazboga\main.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, executor, types
ImportError: cannot import name 'executor' from 'aiogram' (C:\Python312\Lib\aiogram\__init__.py)

**Comment by dimondevceo** [comment]
Купи доступ к API
