### ISSUE TITLE
git clone https://github.com/SegYT/glazboga cd glazboga pip install -r requirements.txt


### ISSUE THREAD

**Issue by VladGor31** [dimondevceo/glazboga#17]
Глаз

git clone https://github.com/SegYT/glazboga cd glazboga pip install -r requirements.txt

**Comment by VladGor31** [comment]
> Глаз
> 
> git clone https://github.com/SegYT/glazboga cd glazboga pip install -r requirements.txt

git clone https://github.com/SegYT/glazboga cd glazboga pip install -r requirements.txt

**Comment by dimondevceo** [comment]
Сделал
