### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by Dastoring** [dimondevceo/glazboga#4]
переделывай

**Comment by dimondevceo** [comment]
@Dastoring не моя проблема что ты ничего не умеешь и ничего не представляешь из себя. Все остальные довольны тем что я сделал, так что пойди куда нибудь и там по ной. Я с слабаками и неучами не общаюсь.

**Comment by GT-leymon** [comment]
бот кста реал не работает

**Comment by dimondevceo** [comment]
@GT-leymon Потому что нужно апи подключить. Любому нормальному программисту это как 2 + 2. Если даже такую банальную вещь не умеешь делать, то не лезь туда куда не надо.

**Comment by dimondevceo** [comment]
Объясняю для тупых:

API для бота платный и его нужно подключать чтобы бот работал.

Нет денег? - Не пользуйся.

Не знаешь как подключить? - Не пользуйся.

Все очень просто.

А те которые знают как, спасибо вам, уважаю, ведь теперь в мире, если ты решишь 2 + 2, то ты гений.

**Comment by GT-leymon** [comment]
> Объясняю для тупых:
> 
> API для бота платный и его нужно подключать чтобы бот работал.
> 
> Нет денег? - Не пользуйся.
> 
> Не знаешь как подключить? - Не пользуйся.
> 
> Все очень просто.
> 
> А те которые знают как, спасибо вам, уважаю, ведь теперь в мире, если ты решишь 2 + 2, то ты гений.

че ты такой агрессивный?
