### ISSUE TITLE
какая версия аиограм

### ISSUE THREAD

**Issue by ggauzin** [dimondevceo/glazboga#9]

**Comment by dimondevceo** [comment]
Вторая. Можешь на третью переписать если удобнее. Я еще не успел это сделать

**Comment by ggauzin** [comment]
если надо, коммитну фикс на 3 версию

вс, 19 мая 2024 г. в 13:14, DimonDev ***@***.***>:

**Comment by dimondevceo** [comment]
Да, пожалуйста, было бы классно

**Comment by dimondevceo** [comment]
Уже переписал все на новый Aiogram 3, теперь все красиво и удобно
